config/routes.rb
DiAndBi::Application.routes.draw do
  resources :products, :brands, :sales

  match 'customers/search/'  => 'customers#search', :as=>'search_customer', :via=>:post
  match 'products/search/'  =>  'products#search',  :as=>'search_product',  :via=>:post
  
  match 'surtir'  =>  'stocks#new', :as =>  'new_store_stock',  :via  =>  :get
  match 'surtir'  =>  'stocks#create', :via  =>  :post
  match 'stock/:id' =>  'stocks#show',  :via  =>  :get, :as => 'store_stock'

end

app/models/address.rb
class Address < ActiveRecord::Base
  validates_numericality_of :zip
  validates_length_of  :zip, :is  => 5
  validates_presence_of :street    
end

app/models/boss.rb
class Boss < User
  has_many  :stores
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  validates_presence_of :name 
  validates_length_of :name , :minimum =>  1
  has_many  :products
  
  before_save {|brand| brand.name.capitalize! }
end

app/models/customer.rb
class Customer < User
  
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  STATUS  = ['pendiente','entregado'].freeze
  attr_protected  :status
  
  validates_presence_of :customer, :shipping_address, :sale , :status,  :due_date
  validates_inclusion_of  :status,  :in =>  STATUS
  validate :future_due_date
  before_validation :set_status
  
  belongs_to  :customer
  belongs_to  :shipping_address,  :class_name =>  "Address",  :validate =>  true
  belongs_to  :sale
  belongs_to  :owner            , :class_name =>  "User"
  
  accepts_nested_attributes_for :shipping_address    
  
  private
    def future_due_date
      self.due_date = Date.today + 1.day  if self.due_date.nil?
      errors.add :due_date, "Cant deliver in the past" if self.due_date < Date.today
    end
    
    def set_status  
      self.status = STATUS[0] if self.new_record?
    end
end

app/models/employee.rb
class Employee < User  
end

app/models/messenger.rb
class Messenger < Employee
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name,  :base_price,  :brand
  validates_numericality_of :base_price, :greater_than  => 0.0
  
  belongs_to  :brand
  
  has_many  :sale_products
  has_many  :sales,   :through  =>  :sale_products
  
  has_many  :stock_products
  has_many  :stocks,  :through  =>  :stock_products
  
  def brand_name
    self.brand.name if brand
  end
  
  def brand_name=(attributes)
    self.brand = Brand.find_by_name(attributes)   
  end
  
  def complete_name
    brand_name + ', ' + name
  end
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  validates_presence_of :total, :dealer, :customer, :store
  validates_numericality_of :total, :greater_than => 0.0 
  validate :store_has_stock_products

  belongs_to  :dealer   ,         :class_name =>  'User'
  belongs_to  :customer ,         :class_name =>  'User'
  belongs_to  :store
  
  has_many    :sale_products
  has_many    :products,  :through  =>  :sale_products
  
  #accepts_nested_attributes_for :customer
  #accepts_nested_attributes_for :sale_products
 
  before_validation   :set_total
  before_save         :stock_math

    
  private 
    def set_total
      counter = 0
      self.sale_products.each{|p| counter +=  ((p.price || p.product.base_price) * p.quantity) }
      self.total  = counter
    end  
    
    def stock_math  ## StockProducts are the products present in a store. CANT sell if you have no stock products
      stock = store.stock          
      sale_products.each do |sp|
        stp = stock.stock_products.where(:product_id=>sp.product_id).first
        raise "No stock Products" if stp.nil?
        if stp.quantity >= sp.quantity
          stp.update_attribute :quantity, stp.quantity -= sp.quantity
        end
      end
    end
    
    def store_has_stock_products
      if store.stock.stock_products.empty?
        p "No stock Products"
        errors.add(:base, "No tienes productos en el Stock de Esta tienda.")
      end
    end
end

app/models/sale_product.rb
class SaleProduct < ActiveRecord::Base
  validates_presence_of :price, :quantity
  validates_numericality_of :price, :greater_than =>  0.0
  validates_numericality_of :quantity, :greater_than => 0
  belongs_to  :product
  belongs_to  :sale               
  
  before_validation :set_price
  
  def name
    product.name  if product
  end
  
  def name=(name)
    product = Product.find_or_create_by_name(name)
  end
  
  private
    def set_price
      self.price  = self.product.base_price if self.price.nil?
    end
    
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  validates_presence_of :store
  belongs_to  :store
  
  has_many  :stock_products,  :autosave=>true
  has_many  :products,  :through  =>  :stock_products
  
  accepts_nested_attributes_for :stock_products
      
end

app/models/stock_product.rb
require 'ostruct'

class StockProduct < ActiveRecord::Base
  PERISHABLE_TAGS = [OpenStruct.new(:tag=>'1 mes', :date=>Date.today + 1.month),
                     OpenStruct.new(:tag=>'3 meses', :date=>Date.today + 3.months),
                     OpenStruct.new(:tag=>'6 meses', :date=>Date.today + 6.months),
                     OpenStruct.new(:tag=>'1 Ano', :date=>Date.today + 1.year)]
                     
                     
  validates_presence_of :product, :stock, :quantity
  validates_numericality_of :quantity,  :greater_than =>  0
  
  belongs_to  :product
  belongs_to  :stock
end

app/models/store.rb
class Store < ActiveRecord::Base
  validates_presence_of :name, :address
  
  belongs_to  :address
  belongs_to  :boss
  has_many    :sales
  has_one     :stock
  
  before_create :give_a_stock  
  
  accepts_nested_attributes_for :address, :stock
  
  private 
    def give_a_stock
      self.build_stock  if self.new_record?
    end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name
  belongs_to  :address
  accepts_nested_attributes_for :address
  has_many  :sales, :foreign_key  =>  "dealer_id"
end 

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def create
    @brand  = Brand.new(params[:brand])
    
    respond_to do |format|     
        format.js   { @brand  } 
        format.html { render :action=>'new', :controller=>'products'}        
    end
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new    
    @sale = Sale.new
  end
    
  def create    
    customer  = Customer.find params[:customer_id].slice(/\d/)
    @sale = Sale.new(params[:sale])
    @sale.customer  = customer
    @sale.sale_products << params[:sale_sale_product].map{|sp| SaleProduct.new sp }
    @sale.save    
    redirect_to new_sale_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  ## Controlador para surtir a una tienda.
  def new
    @stores = Store.all
    @products = Brand.includes(:products).all
  end
  
  def create
    @store  = Store.find(params[:store_id])
    @store.stock.stock_products.build(params[:stock_products])
    @store.save ?
      redirect_to(new_store_stock_path) :
      render(:action=>'new')
  end
  def show
    @store  = Store.includes({:stock => {:stock_products => :product}}).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_brand_name_select(options={})
    product = options[:product].brand_name if options[:product]
    brand   = options[:brand].name  if options[:brand]
    options_for_select(Brand.all.map{|b| [b.name, b.name]} + [['otra','otra']], (product || brand))
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/sales/_sale_product_fields.html.haml
%p
  = label_tag 'name' , "Nombre"
  = text_field_tag  'sale_sale_product[]name',nil,:class=>'sale_product_name'
  = hidden_field_tag  'sale_sale_product[]product_id'
  = label_tag :price, "$"
  = text_field_tag  'sale_sale_product[]price', nil,:size=>4
  = label_tag :quantity,  "Cantidad"
  = text_field_tag  'sale_sale_product[]quantity', nil, :size=>4
  = link_to_function  image_tag('icons/delete.png'), "$(this).parent().remove()"

app/views/sales/new.html.haml
=content_for :scripts do 
  =javascript_include_tag 'jquery-ui.js', 'sale_form.js'
=content_for :css do
  =stylesheet_link_tag 'cupertino/cupertino.css'
  
%h1 Nueva Venta

.grid_8  
  = form_for @sale do |t|
    = field_set_tag 'Quien hizo la venta' do
      = t.label :store_id, 'Sucursal'
      = t.select :store_id, Store.all.collect{|d| [d.name, d.id]}
    
      = t.label :dealer_id,'Vendedor'
      = t.select :dealer_id, Employee.all.collect{|u| [u.name, u.id]}
    
    = field_set_tag 'Cliente' do
      = fields_for :customer do
        = label_tag :name,'Nombre'
        = text_field_tag :customer_name
        = hidden_field_tag  :customer_id
    
    = field_set_tag 'Produtos', :id=>'fields_for_products' do
      = render :partial => "sale_product_fields"
      = link_to_function image_tag('icons/add.png')  do |page|
        - page['#fields_for_products'].prepend render :partial =>  "sale_product_fields"
        - page << "autocompleteFields();"
      Total: 

      
      
    .action
      = t.submit 'Vender'

.grid_4
  #customer-finder
    =form_for :customer, :url=>search_customer_path, :html=>{:method=>'post', :id=>"customer-finder-form"}, :remote=>true do
      =text_field_tag :customer_name
      =submit_tag 'Buscar'
    =image_tag 'loader.gif', :id=>'loader', :style=>"display:none"
    #customers-results

app/views/stocks/_stock_products_fields.html.haml
%div
  =select_tag 'stock_products[]product_id', option_groups_from_collection_for_select(@products, :products, :name, :id, :name)
  =label_tag  'stock_products[]quantity', "Cantidad"
  =number_field_tag 'stock_products[]quantity', 1,:size=>4, :in=>1..300
  =label_tag  'stock_products[]perish_on', "Caduca en"
  =select_tag 'stock_products[]perish_on', options_from_collection_for_select(StockProduct::PERISHABLE_TAGS, 'date', 'tag')
  =link_to_function image_tag('icons/delete.png'), "$(this).parent().slideUp()"

app/views/stocks/new.html.haml
%h1
  Surtir a sucursal
  
.grid_8
  =form_tag do
    =label_tag  :store_id, 'Tienda a surtir'
    =select_tag :store_id, options_from_collection_for_select(@stores, 'id',  'name')
    =field_set_tag 'Productos', :id=>"stock_products_fields" do
      =link_to_function image_tag('icons/add.png') do |page|
        - page['#stock_products_fields'].append render :partial =>  "stock_products_fields"
      = render :partial => "stock_products_fields"      
    = submit_tag 'Surtir'
.grid_4
  =link_to "Altenia", store_stock_path(:id=> 1)

app/views/stocks/show.html.haml
.grid_8
  %h1
    Stock de 
    = @store.name
  
  %table
    %tr
      %th Cantidad
      %th Producto
      %th Expiracion
    -@store.stock.stock_products.each do |sp|
      %tr
        %td=sp.quantity
        %td=sp.product.complete_name
        %td=sp.perish_on